export function ConvertMana(mana) {
  const manaMap = {
    "1": "s1",
    "2": "s2",
    "3": "s3",
    "4": "s4",
    "5": "s5",
    "6": "s6",
    "7": "s7",
    "8": "s8",
    "9": "s9",
    "10": "s10",
    "11": "s11",
    "12": "s12",
    "13": "s13",
    "14": "s14",
    "15": "s15",
    "16": "s16",
    "17": "s17",
    "18": "s18",
    "19": "s19",
    "20": "s20",
    "G": "sg",
    "X": "sx",
    "Y": "sy",
    "Z": "sz",
    "W": "sw",
    "U": "su",
    "B": "sb",
    "R": "sr",
    "S": "ss",
    "C": "sc",
    "W/U": "swu",
    "W/B": "swb",
    "B/R": "sbr",
    "B/G": "sbg",
    "U/B": "sub",
    "U/R": "sur",
    "R/G": "srg",
    "R/W": "srw",
    "G/W": "sgw",
    "G/U": "sgu",
    "2/W": "s2w",
    "2/U": "s2u",
    "2/B": "s2b",
    "2/R": "s2r",
    "2/G": "s2g",
    "W/P": "swp",
    "U/P": "sup",
    "B/P": "sbp",
    "R/P": "srp",
    "G/P": "sgp",
  };

  return manaMap[mana] || "st";
}
