export function ConvertMana(mana) {
  switch (mana) {
    case "1":
      return "s1";
    case "2":
      return "s2";
    case "3":
      return "s3";
    case "4":
      return "s4";
    case "5":
      return "s5";
    case "6":
      return "s6";
    case "7":
      return "s7";
    case "8":
      return "s8";
    case "9":
      return "s9";
    case "10":
      return "s10";
    case "11":
      return "s11";
    case "12":
      return "12";
    case "13":
      return "s13";
    case "14":
      return "s14";
    case "15":
      return "s15";
    case "16":
      return "s16";
    case "17":
      return "s17";
    case "18":
      return "s18";
    case "19":
      return "s19";
    case "20":
      return "s20";
    case "G":
      return "sg";
    case "X":
      return "sx";
    case "Y":
      return "sy";
    case "Z":
      return "sz";
    case "W":
      return "sw";
    case "U":
      return "su";
    case "B":
      return "sb";
    case "R":
      return "sr";
    case "S":
      return "ss";
    case "C":
      return "sc";
    case "W/U":
      return "swu";
    case "W/B":
      return "swb";
    case "B/R":
      return "sbr";
    case "B/G":
      return "sbg";
    case "U/B":
      return "sub";
    case "U/R":
      return "sur";
    case "R/G":
      return "srg";
    case "R/W":
      return "srw";
    case "G/W":
      return "sgw";
    case "G/U":
      return "sgu";
    case "2/W":
      return "s2w";
    case "2/U":
      return "s2u";
    case "2/B":
      return "s2b";
    case "2/R":
      return "s2r";
    case "2/G":
      return "s2g";
    case "W/P":
      return "swp";
    case "U/P":
      return "sup";
    case "B/P":
      return "sbp";
    case "R/P":
      return "srp";
    case "G/P":
      return "sgp";
    default:
      //return turn img none found
      return "st";
  }
}
